# Generated by Django 4.0.7 on 2022-09-16 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PNLF_CRUD', '0002_team_team_coach'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='player_Position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PNLF_CRUD.position', verbose_name='Posición del jugador'),
        ),
        migrations.AlterField(
            model_name='player',
            name='player_Team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PNLF_CRUD.team', verbose_name='Equipo del jugador'),
        ),
    ]
