# Generated by Django 4.0.7 on 2022-09-16 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PNLF_CRUD', '0004_alter_position_pos_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='team_University',
            field=models.CharField(default='-', max_length=50, verbose_name='Universidad del equipo'),
        ),
    ]
